// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHREENHANPQrsHjaWLAg2p-oNabDxNXmI',
    appId: '1:308978304668:web:2ac8902568db975d660f59',
    messagingSenderId: '308978304668',
    projectId: 'omega-chat-10731',
    authDomain: 'omega-chat-10731.firebaseapp.com',
    storageBucket: 'omega-chat-10731.appspot.com',
    measurementId: 'G-DMRHYJ6FMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrPjy29-Qkes10T5PEA9VlqbD-uytmkVA',
    appId: '1:308978304668:android:a7dc4579fc2dbc95660f59',
    messagingSenderId: '308978304668',
    projectId: 'omega-chat-10731',
    storageBucket: 'omega-chat-10731.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7tpBabTAmK4PWMCb4f3StFvmcy1ykKmQ',
    appId: '1:308978304668:ios:c7f0670dba79bf6f660f59',
    messagingSenderId: '308978304668',
    projectId: 'omega-chat-10731',
    storageBucket: 'omega-chat-10731.appspot.com',
    iosClientId: '308978304668-p93g54loh6sqirdqdk1ai50psdg8cv15.apps.googleusercontent.com',
    iosBundleId: 'com.example.omegaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7tpBabTAmK4PWMCb4f3StFvmcy1ykKmQ',
    appId: '1:308978304668:ios:03335ee0bd6efd2f660f59',
    messagingSenderId: '308978304668',
    projectId: 'omega-chat-10731',
    storageBucket: 'omega-chat-10731.appspot.com',
    iosClientId: '308978304668-mj6b7kpfojldjg9u51hitjmotkph2q2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.omegaChat.RunnerTests',
  );
}
